# Generated by Django 4.2.7 on 2026-05-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blotter_Module', '0006_blotter_approved_at_blotter_approved_by_and_more'),
        ('staff_module', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('kapitan', 'Kapitan Appointment'), ('blotter_hearing', 'Blotter Hearing')], default='kapitan', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='blotter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='Blotter_Module.blotter'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hearing_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
