# Generated by Django 4.2.7 on 2026-05-05 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff_module', '0005_appointment_appointment_type_appointment_blotter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(default='Barangay Poblacion', max_length=200)),
                ('barangay_address', models.TextField(default='Poblacion, Santa Catalina, Negros Oriental')),
                ('contact_number', models.CharField(default='(032) 123-4567', max_length=20)),
                ('email', models.EmailField(default='brgy.poblacion@bims.gov.ph', max_length=254)),
                ('office_hours', models.CharField(default='Monday to Friday: 8:00 AM - 5:00 PM', max_length=500)),
                ('email_notifications', models.BooleanField(default=True)),
                ('claim_deadline_days', models.IntegerField(default=7)),
                ('session_timeout', models.IntegerField(default=30)),
                ('min_password_length', models.IntegerField(default=8)),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('view', 'View')], max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
