# Generated by Django 4.2.7 on 2026-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_module', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='affected_resident',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Failed Login'), ('export_attempt', 'Export Attempt'), ('export_approve', 'Export Approve'), ('export_reject', 'Export Reject'), ('certificate_generate', 'Certificate Generate'), ('approve', 'Approve'), ('reject', 'Reject'), ('view', 'View')], max_length=30),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('kapitan', 'Punong Barangay / Kapitan')], default='staff', max_length=50),
        ),
    ]
