# Generated by Django 6.0.4 on 2026-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('clearance', 'Barangay Clearance'), ('indigency', 'Certificate of Indigency'), ('residency', 'Certificate of Residency'), ('id', 'Barangay ID'), ('health_cert', 'Health Certification')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('divorced', 'Divorced'), ('separated', 'Separated')], max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('purpose', models.TextField(blank=True)),
                ('purok', models.CharField(blank=True, max_length=100)),
                ('birthplace', models.CharField(blank=True, max_length=200)),
                ('parents', models.CharField(blank=True, max_length=200)),
                ('date_first_seen', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('date_released', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('processed_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Certificate Request',
                'verbose_name_plural': 'Certificate Requests',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
