# Generated by Django 6.0.4 on 2026-05-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='request_type',
            field=models.CharField(choices=[('clearance', 'Barangay Clearance'), ('indigency', 'Certificate of Indigency'), ('residency', 'Certificate of Residency'), ('id', 'Barangay ID')], max_length=20),
        ),
    ]
