# Generated by Django 6.0.4 on 2026-05-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificaterequest_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
