# Generated by Django 4.2.7 on 2026-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificaterequest_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
