# Generated by Django 4.2.7 on 2026-05-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificaterequest_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='approved_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('for_approval', 'For Kapitan Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
