# Generated by Django 4.2.7 on 2026-05-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_certificaterequest_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='proof_residency',
            field=models.FileField(blank=True, null=True, upload_to='proof_residency/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='valid_id',
            field=models.FileField(blank=True, null=True, upload_to='valid_ids/%Y/%m/%d/'),
        ),
    ]
