# Generated by Django 4.2.7 on 2026-05-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificaterequest_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='claim_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
