# Generated by Django 4.2.7 on 2026-05-23 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0008_merge_certificate_templates_and_claim_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatetemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Certificate Template', 'verbose_name_plural': 'Certificate Templates'},
        ),
        migrations.AlterModelOptions(
            name='certificatetemplatepermission',
            options={'verbose_name': 'Certificate Template Permission', 'verbose_name_plural': 'Certificate Template Permissions'},
        ),
        migrations.AlterModelOptions(
            name='certificatetemplateversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Certificate Template Version', 'verbose_name_plural': 'Certificate Template Versions'},
        ),
        migrations.AlterUniqueTogether(
            name='certificatetemplatepermission',
            unique_together={('template', 'role', 'staff_user')},
        ),
        migrations.AlterUniqueTogether(
            name='certificatetemplateversion',
            unique_together={('template', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='certificatetemplate',
            index=models.Index(fields=['template_type', 'is_deleted', 'is_active'], name='certificate_templat_067a64_idx'),
        ),
    ]
