# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=30)),
                ('birthdate', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('civil_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('resident_id', models.CharField(max_length=50, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='residents/%Y/%m/%d/')),
                ('household_number', models.CharField(blank=True, max_length=50)),
                ('voter_status', models.CharField(choices=[('registered', 'Registered'), ('not_registered', 'Not Registered'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['full_name', 'birthdate'], name='accounts_re_full_na_7e1fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['contact_number'], name='accounts_re_contact_ccd270_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['email'], name='accounts_re_email_074965_idx'),
        ),
    ]
