# Generated by Django 4.2.7 on 2026-05-16 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('filtered', 'Filtered residents'), ('senior', 'Senior citizens'), ('youth', 'Youth residents'), ('solo_parent', 'Solo parents'), ('voter_age', 'Voter-age residents'), ('indigent', 'Indigent residents')], default='filtered', max_length=30)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='resident',
            name='barangay',
            field=models.CharField(default='Poblacion', max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_residents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_indigent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_solo_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='municipality',
            field=models.CharField(default='Santa Catalina', max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='national_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='resident',
            name='national_id_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='resident',
            name='occupation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='resident',
            name='privacy_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='province',
            field=models.CharField(default='Negros Oriental', max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='purok',
            field=models.CharField(blank=True, choices=[('purok_1', 'Purok 1'), ('purok_2', 'Purok 2'), ('purok_3', 'Purok 3'), ('purok_4', 'Purok 4'), ('purok_5', 'Purok 5'), ('purok_6', 'Purok 6'), ('purok_7', 'Purok 7')], max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['household_number'], name='accounts_re_househo_039609_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['is_deleted'], name='accounts_re_is_dele_179bb8_idx'),
        ),
        migrations.AddField(
            model_name='residentexportrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_resident_exports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentexportrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_export_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
