# Generated by Django 6.0.4 on 2026-04-26 04:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blotter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blotter_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('complainant_name', models.CharField(max_length=255)),
                ('complainant_address', models.TextField(blank=True, null=True)),
                ('complainant_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('complainant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_address', models.TextField(blank=True, null=True)),
                ('respondent_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('incident_type', models.CharField(choices=[('physical_injury', 'Physical Injury'), ('threat', 'Threat/Intimidation'), ('property_damage', 'Property Damage'), ('domestic', 'Domestic Violence'), ('others', 'Others')], default='others', max_length=50)),
                ('incident_date', models.DateField(default=django.utils.timezone.now)),
                ('incident_location', models.TextField()),
                ('incident_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blotters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlotterAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='Blotter_Module.blotter')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Blotter_Module.blotter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['hearing_date'],
            },
        ),
    ]
