# Generated by Django 6.0.4 on 2026-04-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blotter_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blotter',
            name='blotter_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
