# Generated by Django 4.2.7 on 2026-04-29 10:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blotter_Module', '0002_alter_blotter_blotter_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blotter',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_blotters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blotter',
            name='hearing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='hearing_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='initial_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='blotter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Blotter_Module.blotter'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new', 'New Blotter'), ('hearing', 'Hearing Scheduled'), ('reminder', 'Hearing Reminder'), ('status', 'Status Update'), ('resolved', 'Case Resolved')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hearing_type',
            field=models.CharField(choices=[('initial', 'Initial Hearing'), ('follow_up', 'Follow-up Hearing'), ('conciliation', 'Conciliation'), ('final', 'Final Hearing')], default='initial', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(default='Barangay Hall', max_length=200),
        ),
        migrations.AddField(
            model_name='schedule',
            name='outcome',
            field=models.CharField(choices=[('pending', 'Pending'), ('adjourned', 'Adjourned'), ('settled', 'Settled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='outcome_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='rescheduled_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blotter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blotters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blotter',
            name='incident_type',
            field=models.CharField(choices=[('physical_injury', 'Physical Injury'), ('threat', 'Threat/Intimidation'), ('property_damage', 'Property Damage'), ('domestic', 'Domestic Violence'), ('theft', 'Theft/Robbery'), ('harassment', 'Harassment'), ('land_dispute', 'Land Dispute'), ('others', 'Others')], default='others', max_length=50),
        ),
        migrations.AlterField(
            model_name='blotter',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('unsettled', 'Unsettled'), ('dismissed', 'Dismissed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='blotterauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('status_change', 'Status Change'), ('schedule', 'Schedule'), ('upload_evidence', 'Upload Evidence')], max_length=100),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('evidence_type', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'mp4', 'mp3', 'doc', 'docx'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('blotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='Blotter_Module.blotter')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlotterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blotter_Module.blotter')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
