# Generated by Django 4.2.7 on 2026-04-29 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blotter_Module', '0003_blotter_assigned_officer_blotter_hearing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blotter',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='purpose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_blotters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blotter',
            name='staff_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='verification_status',
            field=models.CharField(default='pending_verification', max_length=30),
        ),
        migrations.AddField(
            model_name='blotter',
            name='verified_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
