# Generated by Django 4.2.7 on 2026-04-29 15:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blotter_Module', '0004_blotter_ip_address_blotter_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blotter',
            name='id_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='id_verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='blotter',
            name='id_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='id_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blotter',
            name='valid_id_file',
            field=models.FileField(blank=True, null=True, upload_to='valid_ids/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='blotter',
            name='valid_id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('email', 'Email Verification'), ('id_card', 'Valid ID Verification')], max_length=20, null=True),
        ),
    ]
