# Generated by Django 4.2.7 on 2026-05-01 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blotter_Module', '0005_blotter_id_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blotter',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_blotters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blotter',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='Blotter_Module.blotter'),
        ),
        migrations.AddField(
            model_name='blotter',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blotter',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blotterauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('status_change', 'Status Change'), ('schedule', 'Schedule'), ('upload_evidence', 'Upload Evidence'), ('approve', 'Approve'), ('reject', 'Reject'), ('mark_duplicate', 'Mark as Duplicate')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new', 'New Blotter'), ('hearing', 'Hearing Scheduled'), ('reminder', 'Hearing Reminder'), ('status', 'Status Update'), ('resolved', 'Case Resolved'), ('approved', 'Blotter Approved'), ('rejected', 'Blotter Rejected')], default='new', max_length=20),
        ),
    ]
