# Generated by Django 4.2.7 on 2026-05-05 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blotter_Module', '0006_blotter_approved_at_blotter_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'Evidences'},
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='evidence_type',
        ),
        migrations.AddField(
            model_name='evidence',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('other', 'Other')], default='image', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to='evidence/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL),
        ),
    ]
