# Generated by Django 4.2.7 on 2026-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blotter_Module', '0007_alter_evidence_options_remove_evidence_evidence_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('other', 'Other')], default='image', max_length=20),
        ),
    ]
