# Generated by Codex on 2026-05-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blotter_Module', '0008_alter_evidence_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blotter',
            name='complainant_barangay',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blotter',
            name='complainant_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='complainant_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='blotter',
            name='complainant_municipality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blotter',
            name='complainant_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blotter',
            name='complainant_street_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
